Repository ishitakapoor26/HealthBliss-Hacktoberfest2022, pull requests merged in 2021-12, with the labels that each got.

#64 Added icons to how to support section (#61)
  assets/css/fontawesome.css
  assets/css/style.css
  assets/webfonts/fa-brands-400.eot
  assets/webfonts/fa-brands-400.svg
  assets/webfonts/fa-brands-400.ttf
  assets/webfonts/fa-brands-400.woff
  assets/webfonts/fa-brands-400.woff2
  assets/webfonts/fa-duotone-900.eot
  assets/webfonts/fa-duotone-900.svg
  assets/webfonts/fa-duotone-900.ttf
  assets/webfonts/fa-duotone-900.woff
  assets/webfonts/fa-duotone-900.woff2
  assets/webfonts/fa-light-300.eot
  assets/webfonts/fa-light-300.svg
  assets/webfonts/fa-light-300.ttf
  assets/webfonts/fa-light-300.woff
  assets/webfonts/fa-light-300.woff2
  assets/webfonts/fa-regular-400.eot
  assets/webfonts/fa-regular-400.svg
  assets/webfonts/fa-regular-400.ttf
  assets/webfonts/fa-regular-400.woff
  assets/webfonts/fa-regular-400.woff2
  assets/webfonts/fa-solid-900.eot
  assets/webfonts/fa-solid-900.svg
  assets/webfonts/fa-solid-900.ttf
  assets/webfonts/fa-solid-900.woff
  assets/webfonts/fa-solid-900.woff2
  index.html
Labels: enhancement, SWoC, SWoC'21

#58 Fixed navbar font and fixed navbar icon in mobile view
  about us/assets/css/style.css
  assets/css/style.css
Labels: enhancement, good first issue, SWoC, SWoC'21

#67 height issue is fixed on mental health section
  index.html
Labels: enhancement, SWoC, SWoC'21

#55 Fixing Portfolio filters's Allignment in Mobile View
  assets/css/style.css
Labels: bug, SWoC, SWoC'21, Assigned
