Repository ishitakapoor26/HealthBliss-Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#99 Added a Social Media Button and Added a Timing Section in Website
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, Assigned

#96 fixed icons overlapping text in teams section
  assets/css/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, Assigned

#107 added some media query in style.css to change the opacity of header c…
  assets/css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Assigned

#137 Fix footer design
  about us/mental_health.html
  about us/suicide_info.html
  about us/tabt.html
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#131 resolved issue #124
  about us/forms/contact.php
  assets/css/button.css
  assets/css/style.css
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#113 Added forgot password option in login page & made button beautiful
  assets/css/login.css
  loginpage.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
